# -*- coding: utf-8 -*-
"""GeminiAPI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wb5pG0PKhPafxGbV8uBvnK5OYS0FPrEw
"""

!pip install google-adk -q

import os
import re
import asyncio

try:
    from google.colab import auth as colab_auth
    colab_auth.authenticate_user()
except ImportError:
    pass

import google.auth

_credentials, project_id = google.auth.default()
project_id = "project-a7706442-5d29-44c1-ba3"
if not project_id:
    raise ValueError(
        "No GCP project ID found. Set GOOGLE_CLOUD_PROJECT or run: gcloud config set project YOUR_PROJECT"
    )
os.environ["GOOGLE_CLOUD_PROJECT"] = project_id
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "1"
if "GOOGLE_CLOUD_LOCATION" not in os.environ:
    os.environ["GOOGLE_CLOUD_LOCATION"] = "global"
LOCATION = os.environ["GOOGLE_CLOUD_LOCATION"]

from IPython.display import display, Markdown
from google.adk.agents import Agent, SequentialAgent, LoopAgent, ParallelAgent
from google.adk.tools import google_search, ToolContext
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService, Session
from google.genai.types import Content, Part

print("✅ Libraries loaded. ADK uses Vertex AI via ADC. Project:", project_id, "| Location:", LOCATION)

async def run_agent_query(agent: Agent, query: str, session: Session, user_id: str, is_router: bool = False):
    """Initializes a runner and executes a query for a given agent and session."""
    print(f"\n🚀 Running query for agent: '{agent.name}' in session: '{session.id}'...")

    runner = Runner(
        agent=agent,
        session_service=session_service,
        app_name=agent.name
    )

    final_response = ""
    try:
        async for event in runner.run_async(
            user_id=user_id,
            session_id=session.id,
            new_message=Content(parts=[Part(text=query)], role="user")
        ):
            if not is_router:
                # Let's see what the agent is thinking!
                print(f"EVENT: {event}")
            if event.is_final_response():
                final_response = event.content.parts[0].text
    except Exception as e:
        final_response = f"An error occurred: {e}"

    if not is_router:
     print("\n" + "-"*50)
     print("✅ Final Response:")
     display(Markdown(final_response))
     print("-"*50 + "\n")

    return final_response

# --- Initialize our Session Service ---
# This one service will manage all the different sessions in our notebook.
session_service = InMemorySessionService()
my_user_id = "adk_adventurer_001"

# --- Diet Plan Agent ---

# A tool to signal that the loop should terminate
COMPLETION_PHRASE = "The meal meets all nutritional constraints."

def exit_loop(tool_context: ToolContext):
  """Call this function ONLY when the meal is approved, signaling the loop should end."""
  print(f"  [Tool Call] exit_loop triggered by {tool_context.agent_name}")
  tool_context.actions.escalate = True
  return {}

# Agent 1: Proposes an initial meal (Has Search)
meal_finder_agent = Agent(
    name="meal_finder_agent",
    model="gemini-2.5-flash",
    tools=[google_search],
    instruction="""Taske the input for target marcro for each day and recommend a 1 day meal plan for breakfast, lunch, dinner
    Constraint: {{processed_constraints}}""",
    output_key="meal_plan"
)

# Agent 2 (in loop): Critiques the meal against macros (No Tools)
critic_agent = Agent(
    name="critic_agent",
    model="gemini-2.5-flash",
    tools=[exit_loop],
    instruction=f"""You are a strict, robotic nutritionist. Evaluate the current meal against the user's prompt.
    Original Request: {{session.query}}
    Current Meal: {{meal_plan}}
    If the meal does not meet the macro targets perfectly, provide a brief critique of what is missing (e.g., 'Protein is 20g short. Add 1 scoop of pea protein.').
    If the meal MEETS the targets, you MUST immediately call the 'exit_loop' tool.""",
    output_key="criticism"
)

# Agent 3 (in loop): Refines the meal based on critique or exits (Only Custom Tool)
refiner_agent = Agent(
    name="refiner_agent",
    model="gemini-2.5-flash",
    instruction=f"""You are a strict dietary modifier.
    Critique: {{criticism}}

    ELSE, generate a new meal string that incorporates the critique.
    DO NOT be conversational. Output ONLY the new string: 'Meal: [Updated Name], Macros: [Updated Macros]'.""",
    output_key="meal_plan"
)

# ✨ The LoopAgent orchestrates the meal evaluation cycle ✨
meal_refinement_loop = LoopAgent(
    name="meal_refinement_loop",
    sub_agents=[critic_agent, refiner_agent],
    max_iterations=2
)

# Agent 4: Schedules the approved meal
# schedule_planner_agent = Agent(
#     name="schedule_planner_agent",
#     model="gemini-2.5-flash",
#     instruction="""Take the final meal plan and format it nicely into a schedule.
#     Final Meal: {{meal_plan}}"""
# )

# ✨ The SequentialAgent puts it all together ✨
iterative_diet_workflow = SequentialAgent(
    name="iterative_diet_workflow",
    sub_agents=[meal_finder_agent, meal_refinement_loop],
    description="A workflow that finds, iteratively refines to hit macro goals, and schedules a meal plan for 1 days."
)

## Main Agent

medical_agent = Agent(
    name="medical_agent",
    model="gemini-2.5-flash",
    instruction="""
    Act as a Clinical Nutrition & Fitness Architect. Your task is to take my personal data (Age, Weight, Goals, Health Conditions, and Schedule) and transform it into a standardized processed_constraints block.

    Output Requirements:

    Calculate TDEE and Macros based on my profile.

    Convert health conditions into specific 'Dietary Filters' (e.g., Hypertension = Low Sodium).

    Map my sleep schedule to a 'Timing Window' (8:30 AM start, ending 3 hours before sleep).

    Identify 'Restricted Exercises/Meals' based on any injuries or medical history.

    Strict Format: You must output the result exactly in this Markdown structure:

    processed_constraints =
    Daily Target Profile:
    Total Calories: [X] kcal
    Macro Split: [P]g Protein / [C]g Carbs / [F]g Fat
    Dietary Filters: [List here]
    Timing Window: [Times here]
    Activity Context: [Workout priority here]
    Restricted Exercises: [List]
    Restricted Meals: [List]
    Allergies: [List]
    Injuries: [List]
    """,
    output_key="processed_constraints"
)

workout_plan_agent = Agent(
    name="workout_plan_agent",
    model="gemini-2.5-flash",
    instruction="""Create a workout plan for 1 day using this constraints: {{processed_constraints}}
    """,
    output_key="workout_plan"
)

parallel_plan_agent = ParallelAgent(
    name="parallel_plan_agent",
    sub_agents=[workout_plan_agent, iterative_diet_workflow]
)

final_plan_agent = Agent(
    name="final_agent",
    model="gemini-2.5-flash",
    instruction="""Take the final meal plan and workout plan and format it nicely into a schedule.
    Final Meal Plan: {{meal_plan}}
    Workout Plan: {{workout_plan}}"""
)

main_agent = SequentialAgent(
    name="main_agent",
    sub_agents=[medical_agent, parallel_plan_agent, final_plan_agent]
)

planner_agent = Agent(
    name="final_agent",
    model="gemini-2.5-flash",
    sub_agents=[main_agent]
)



async def run_plan():
    # Create a new, single-use session for this query
    session = await session_service.create_session(
        app_name=planner_agent.name,
        user_id=my_user_id
    )

    query = """Take the processed_constraints and find a 4-meal distribution that sums up to the target macros precisely.



    """

    # We call our existing helper function with the top-level orchestrator agent
    await run_agent_query(planner_agent, query, session, my_user_id)

# Run the test
await run_plan()

